spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: appuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: transaction-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

account-service:
  url: https://localhost:8443

mtls:
  client:
    key-store: classpath:ssl/transaction-service.p12
    key-store-password: changeit
    trust-store: classpath:ssl/transaction-truststore.p12
    trust-store-password: changeit

logging:
  level:
    com.banking.transaction: DEBUG

server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:ssl/transaction-service-server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    trust-store: classpath:ssl/transaction-service-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: need